--liquibase formatted.sql
--changeset michael.cawayan:MONITOR.V_RTDM_LOG_IF143_REL contextFilter:PH endDelimiter:/ runOnChange:true


  CREATE OR REPLACE EDITIONABLE VIEW "MONITOR"."V_RTDM_LOG_IF143_REL" (
    "CORRELATION_ID"
    , "EVENT_NAME"
    , "EVENT_TIMESTAMP"
    , "STATUS"
    , "STATUS_DESCRIPTION"
    , "RTDM_HOSTNAME"
    ,ACCOUNT_STATUS	
,ACCOUNT_TYPE	
,ACCOUNT_NUMBER	
,EVENT_TYPE_ENUM	
,TXN_SOURCEID_SOURCE_SYSTEM	
,TXN_SOURCEID_SOURCE_TXID	
,TRUNCATED_PAN
,AUTH_AUTHORIZATION_MODE	
,AUTH_CU_MCC	 
,AUTH_CU_CA_CITY	
,AUTH_CU_CA_COUNTRY_CODE	
,AUTH_CU_CA_NAME	
,AUTH_BILLING_AMOUNT_VALUE
,AUTH_TXN_AMOUNT_VALUE	
,AUTH_TXN_AMOUNT_CURRENCY
,AUTH_TYPE	
,UPDATED_DTTM	
,LOG_SOURCE	
) 
    AS SELECT 
    correlation_id
    , event_name
    , event_timestamp
    , status
    , status_description
    , rtdm_hostname
    ,ACCOUNT_STATUS	
,ACCOUNT_TYPE	
,ACCOUNT_NUMBER	
,EVENT_TYPE_ENUM	
,TXN_SOURCEID_SOURCE_SYSTEM	
,TXN_SOURCEID_SOURCE_TXID	
,TRUNCATED_PAN
,AUTH_AUTHORIZATION_MODE	
,AUTH_CU_MCC	 
,AUTH_CU_CA_CITY	
,AUTH_CU_CA_COUNTRY_CODE	
,AUTH_CU_CA_NAME	
,AUTH_BILLING_AMOUNT_VALUE
,AUTH_TXN_AMOUNT_VALUE	
,AUTH_TXN_AMOUNT_CURRENCY
,AUTH_TYPE	
,UPDATED_DTTM	
,LOG_SOURCE	
FROM monitor.RTDM_LOG_IF143_REL
WHERE 1=2
/
GRANT SELECT, INSERT, UPDATE, DELETE ON "MONITOR"."V_RTDM_LOG_IF143_REL" TO ESP_USER
/
GRANT SELECT ON "MONITOR"."V_RTDM_LOG_IF143_REL" TO HCI_RO_MONITOR
/